def project=""
node {
  stage("Initialize") {
    project = env.PROJECT_NAME
  } 
  stage("Start Build") {
    openshift.withCluster() {
      echo "Hello from project running Jenkins: ${openshift.project()}"
      def bc = openshift.selector( 'buildconfig/s2i-internal-python' )
      def build = bc.startBuild()
      build.logs()
    }
  }
}


podTemplate(
  label: 'skopeo', inheritFrom: 'jenkins-slave-image-mgmt',
  volumes: [secretVolume(secretName: 'ext-registry-secret', mountPath: '/var/run/ext-registry')]
){
  node('skopeo') { 
    stage('Inspect Image') {
      sh """
  
      set +x
      dh_usr=$(cat /var/run/ext-registry/username)
      dh_pwd=$(cat /var/run/ext-registry/password)
      #skopeo inspect --creds user:`cat /var/run/secrets/kubernetes.io/serviceaccount/token` --tls-verify=false docker://docker-registry.default.svc:5000/test/s2i-internal-python:latest
  
      """
    }
  }
}
