def project=""
node {
  stage("Initialize") {
    project = env.PROJECT_NAME
  } 
  stage("Start Build") {
    openshift.withCluster() {
      echo "Hello from project running Jenkins: ${openshift.project()}"
      def bc = openshift.selector( 'buildconfig/s2i-internal-python' )
      def build = bc.startBuild()
      build.logs()
    }
  }
}

node('jenkins-slave-image-mgmt') { 
  stage('Push Image Ext-Reg') {
    sh """
    set +x
    src_creds="user:`cat /var/run/secrets/kubernetes.io/serviceaccount/token`"
    dest_creds="`cat /var/run/dockerhub/username`:`cat /var/run/dockerhub/password`"
    skopeo copy \
      --remove-signatures \
      --src-tls-verify=false \
      --src-creds "\$src_creds" \
      --dest-creds "\$dest_creds" \
      docker://docker-registry.default.svc:5000/test/s2i-internal-python:latest \
      docker://docker.io/propyless/s2i-internal-python
    """
  }
}

